name: "Linting"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - group: linting
            commands: |
              uv run --group linting pylint timebutler_client
              uv run --group linting pylint unittests --rcfile=unittests/.pylintrc
          - group: type_check
            commands: |
              uv run --group type_check mypy --show-error-codes src/timebutler_client --strict
              uv run --group type_check mypy --show-error-codes unittests --strict
          - group: spell_check
            commands: |
              uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt src
              uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt README.md
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Run ${{ matrix.group }}
        run: |
          ${{ matrix.commands }}
